name: omar_ahmed
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  # State Management
  bloc: ^9.0.0

  # Code Generator (Mainly used in with Cubit & Retrofit)
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0

  # For Dependency Injection
  get_it: ^8.0.3

  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.4.0

  # Localization
  intl: ^0.20.2
  # easy_localization: ^3.0.7+1

  # For Splash Screen
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
